; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32_tx_remote]
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
upload_port = /dev/tty.usbmodem2101
monitor_port = /dev/tty.usbmodem2101
board_build.arduino.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	; Enable performance monitoring (set to 1 to enable, 0 to disable)
	-DDEBUG_PERF=0
lib_deps = 
	lib/lvgl
	adafruit/Adafruit ADS1X15@^2.5.0
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
lib_extra_dirs = 
build_src_filter = +<*> +<../lib/lvgl/demos/music/assets/*.c> +<../lib/lvgl/demos/widgets/assets/img_lvgl_logo.c>
platform = espressif32
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.34/platform-espressif32.zip
