// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine Test

#include "ui.h"

void ui_event_comp_BtnTest_BtnTest( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_BtnTest = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      printStuff( e );
}
}

// COMPONENT BtnTest

lv_obj_t *ui_BtnTest_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_BtnTest;
cui_BtnTest = lv_button_create(comp_parent);
lv_obj_set_width( cui_BtnTest, 71);
lv_obj_set_height( cui_BtnTest, 21);
lv_obj_set_x( cui_BtnTest, 118 );
lv_obj_set_y( cui_BtnTest, 0 );
lv_obj_set_align( cui_BtnTest, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_BtnTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( cui_BtnTest, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_BtnTest, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_BtnTest, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(cui_BtnTest, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(cui_BtnTest, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_BtnTest, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_BtnTest, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_BtnTest, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_BtnTest, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(cui_BtnTest, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label4;
cui_Label4 = lv_label_create(cui_BtnTest);
lv_obj_set_width( cui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label4,"Test");

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BTNTEST_NUM);
children[UI_COMP_BTNTEST_BTNTEST] = cui_BtnTest;
children[UI_COMP_BTNTEST_LABEL4] = cui_Label4;
lv_obj_add_event_cb(cui_BtnTest, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_BtnTest, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_BtnTest, ui_event_comp_BtnTest_BtnTest, LV_EVENT_ALL, children);
ui_comp_BtnTest_create_hook(cui_BtnTest);
return cui_BtnTest; 
}

