// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine Test

#ifndef _UI_COMP_BTNTEST_H
#define _UI_COMP_BTNTEST_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BtnTest
#define UI_COMP_BTNTEST_BTNTEST 0
#define UI_COMP_BTNTEST_LABEL4 1
#define _UI_COMP_BTNTEST_NUM 2
lv_obj_t *ui_BtnTest_create(lv_obj_t *comp_parent);
void ui_event_comp_BtnTest_BtnTest( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
