// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine Test

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_TopPanel;
extern lv_obj_t *ui_Title;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_MainPannel;
extern lv_obj_t *ui_Gimbal1;
extern lv_obj_t *ui_CenterGimbal1;
extern lv_obj_t *ui_InputPanel;
extern lv_obj_t *ui_LblPot1;
extern lv_obj_t *ui_BarPot1;
extern lv_obj_t *ui_EncPanel;
extern lv_obj_t *ui_LblEnc1Val;
extern lv_obj_t *ui_LblENC1;
extern lv_obj_t *ui_TopPanel2;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_BtnTest1;
extern lv_obj_t *ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Button1;
extern lv_obj_t *uic_BtnTest1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

