// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine Test

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BACKGROUND 0
#define UI_THEME_COLOR_FOREGROUND 1
#define UI_THEME_COLOR_COMMENT 2
#define UI_THEME_COLOR_CYAN 3
#define UI_THEME_COLOR_GREEN 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Background[1];
extern const ui_theme_variable_t _ui_theme_alpha_Background[1];

extern const ui_theme_variable_t _ui_theme_color_Foreground[1];
extern const ui_theme_variable_t _ui_theme_alpha_Foreground[1];

extern const ui_theme_variable_t _ui_theme_color_Comment[1];
extern const ui_theme_variable_t _ui_theme_alpha_Comment[1];

extern const ui_theme_variable_t _ui_theme_color_Cyan[1];
extern const ui_theme_variable_t _ui_theme_alpha_Cyan[1];

extern const ui_theme_variable_t _ui_theme_color_Green[1];
extern const ui_theme_variable_t _ui_theme_alpha_Green[1];

extern const uint32_t* ui_theme_colors[1];
extern const uint8_t* ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
