// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine Test

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Background[1] = {0x282A36};
const ui_theme_variable_t _ui_theme_alpha_Background[1] = {255};

const ui_theme_variable_t _ui_theme_color_Foreground[1] = {0xF8F8F2};
const ui_theme_variable_t _ui_theme_alpha_Foreground[1] = {255};

const ui_theme_variable_t _ui_theme_color_Comment[1] = {0x6272A4};
const ui_theme_variable_t _ui_theme_alpha_Comment[1] = {255};

const ui_theme_variable_t _ui_theme_color_Cyan[1] = {0x8BE9FD};
const ui_theme_variable_t _ui_theme_alpha_Cyan[1] = {255};

const ui_theme_variable_t _ui_theme_color_Green[1] = {0x50FA7B};
const ui_theme_variable_t _ui_theme_alpha_Green[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

